-- 003_squads.sql – Static WC 2026 squad data for all 48 teams
-- Based on current/expected squads (June 2025 knowledge)
-- Idempotent: deletes and re-inserts all player rows

DELETE FROM players;

WITH t AS (SELECT fifa_code, id FROM teams)
INSERT INTO players (team_id, name, position, shirt_number, club, is_active, updated_at)
SELECT t.id, p.nm, p.pos, p.num, p.club, true, NOW()
FROM (VALUES

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP A: Mexico · South Africa · South Korea · Czechia
  -- ═══════════════════════════════════════════════════════════════════

  -- Mexico
  ('MEX','Guillermo Ochoa','GK',1,'Club América'),
  ('MEX','Luis Malagón','GK',13,'Club América'),
  ('MEX','Rodolfo Cota','GK',23,'Club León'),
  ('MEX','César Montes','DEF',3,'Monterrey'),
  ('MEX','Johan Vásquez','DEF',5,'Genoa'),
  ('MEX','Gerardo Arteaga','DEF',17,'Getafe'),
  ('MEX','Jesús Gallardo','DEF',16,'Monterrey'),
  ('MEX','Jorge Sánchez','DEF',22,'Ajax'),
  ('MEX','Carlos Salcedo','DEF',4,'Cruz Azul'),
  ('MEX','Edson Álvarez','MID',18,'Chelsea'),
  ('MEX','Carlos Rodríguez','MID',8,'Cruz Azul'),
  ('MEX','Luis Chávez','MID',14,'Pachuca'),
  ('MEX','Roberto Alvarado','MID',11,'Chivas'),
  ('MEX','Héctor Herrera','MID',6,'LA Galaxy'),
  ('MEX','Orbelín Pineda','MID',21,'AEK Athens'),
  ('MEX','Santiago Giménez','FWD',9,'Bayer Leverkusen'),
  ('MEX','Hirving Lozano','FWD',7,'San Diego FC'),
  ('MEX','Henry Martín','FWD',21,'Club América'),
  ('MEX','Raúl Jiménez','FWD',10,'Fulham'),
  ('MEX','Alexis Vega','FWD',20,'Chivas'),

  -- South Africa
  ('RSA','Ronwen Williams','GK',1,'Mamelodi Sundowns'),
  ('RSA','Bruce Bvuma','GK',16,'Kaizer Chiefs'),
  ('RSA','Veli Mothwa','GK',22,'AmaZulu'),
  ('RSA','Siyanda Xulu','DEF',5,'Mamelodi Sundowns'),
  ('RSA','Terrence Mashego','DEF',3,'Mamelodi Sundowns'),
  ('RSA','Reeve Frosler','DEF',2,'Kaizer Chiefs'),
  ('RSA','Mothobi Mvala','DEF',6,'Mamelodi Sundowns'),
  ('RSA','Grant Kekana','DEF',4,'Mamelodi Sundowns'),
  ('RSA','Nyiko Mobbie','DEF',12,'Mamelodi Sundowns'),
  ('RSA','Teboho Mokoena','MID',8,'Mamelodi Sundowns'),
  ('RSA','Themba Zwane','MID',10,'Mamelodi Sundowns'),
  ('RSA','Bongani Zungu','MID',14,'Al-Qadsiah'),
  ('RSA','Ethan Brooks','MID',17,'FK Partizan'),
  ('RSA','Keagan Dolly','MID',11,'Kaizer Chiefs'),
  ('RSA','Lyle Foster','FWD',9,'Burnley'),
  ('RSA','Percy Tau','FWD',20,'Al-Ahly'),
  ('RSA','Evidence Makgopa','FWD',19,'Bayer Leverkusen'),
  ('RSA','Mihlali Mayambela','FWD',18,'FC Zurich'),

  -- South Korea
  ('KOR','Kim Seung-gyu','GK',1,'Al-Shabab'),
  ('KOR','Cho Hyun-woo','GK',21,'Ulsan'),
  ('KOR','Song Bum-keun','GK',23,'Jeonbuk'),
  ('KOR','Kim Min-jae','DEF',3,'Bayern Munich'),
  ('KOR','Kim Jin-su','DEF',15,'Al-Qadsiah'),
  ('KOR','Lee Tae-young','DEF',20,'Al-Ettifaq'),
  ('KOR','Kim Moon-hwan','DEF',2,'Jeonbuk'),
  ('KOR','Park Yong-woo','DEF',4,'Seongnam'),
  ('KOR','Kwon Kyung-won','DEF',5,'Girona'),
  ('KOR','Lee Kang-in','MID',7,'Paris Saint-Germain'),
  ('KOR','Hwang In-beom','MID',8,'Vancouver Whitecaps'),
  ('KOR','Jung Woo-young','MID',13,'Al-Ittihad'),
  ('KOR','Paik Seung-ho','MID',6,'Jeonbuk'),
  ('KOR','Oh Hyeon-gyu','MID',16,'Celtic'),
  ('KOR','Son Heung-min','FWD',7,'Tottenham Hotspur'),
  ('KOR','Hwang Hee-chan','FWD',11,'Wolverhampton'),
  ('KOR','Cho Gue-sung','FWD',9,'Miyagi'),
  ('KOR','Hwang Ui-jo','FWD',10,'Nottingham Forest'),

  -- Czechia
  ('CZE','Jindřich Staněk','GK',1,'Slavia Prague'),
  ('CZE','Matěj Kovář','GK',23,'Bayer Leverkusen'),
  ('CZE','Tomáš Vaclík','GK',13,'FC Zürich'),
  ('CZE','Tomáš Souček','MID',6,'West Ham United'),
  ('CZE','Vladimír Coufal','DEF',2,'West Ham United'),
  ('CZE','Ondřej Duda','MID',10,'Olympiacos'),
  ('CZE','Patrik Schick','FWD',7,'Bayer Leverkusen'),
  ('CZE','Adam Hložek','FWD',11,'Hoffenheim'),
  ('CZE','Lukáš Provod','MID',8,'Slavia Prague'),
  ('CZE','Antonín Barák','MID',17,'Fiorentina'),
  ('CZE','David Jurásek','DEF',3,'Benfica'),
  ('CZE','Tomáš Holeš','DEF',5,'Slavia Prague'),
  ('CZE','Robin Hranáč','DEF',4,'Plzeň'),
  ('CZE','Ladislav Krejčí','DEF',15,'Sparta Prague'),
  ('CZE','Jakub Jankto','MID',18,'Sparta Prague'),
  ('CZE','Tomáš Čvančara','FWD',9,'Mönchengladbach'),
  ('CZE','Jan Kuchta','FWD',21,'Slavia Prague'),
  ('CZE','Pavel Šulc','FWD',19,'Plzeň'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP B: Canada · Bosnia & Herzegovina · Qatar · Switzerland
  -- ═══════════════════════════════════════════════════════════════════

  -- Canada
  ('CAN','Milan Borjan','GK',1,'Red Star Belgrade'),
  ('CAN','James Pantemis','GK',18,'CF Montréal'),
  ('CAN','Dayne St. Clair','GK',22,'Minnesota United'),
  ('CAN','Alphonso Davies','DEF',19,'Bayern Munich'),
  ('CAN','Kamal Miller','DEF',5,'Inter Miami'),
  ('CAN','Derek Cornelius','DEF',3,'Famalicão'),
  ('CAN','Alistair Johnston','DEF',2,'Celtic'),
  ('CAN','Doneil Henry','DEF',4,'Vancouver Whitecaps'),
  ('CAN','Richie Laryea','DEF',22,'Nottingham Forest'),
  ('CAN','Atiba Hutchinson','MID',13,'Beşiktaş'),
  ('CAN','Stephen Eustáquio','MID',7,'FC Porto'),
  ('CAN','Tajon Buchanan','MID',11,'Inter Milan'),
  ('CAN','Samuel Piette','MID',6,'CF Montréal'),
  ('CAN','Charles-Andreas Brym','MID',17,'Göztepe'),
  ('CAN','Jonathan David','FWD',9,'LOSC Lille'),
  ('CAN','Cyle Larin','FWD',10,'Rapid Vienna'),
  ('CAN','Lucas Cavallini','FWD',21,'Vancouver Whitecaps'),
  ('CAN','Jacob Shaffelburg','FWD',15,'Nashville SC'),

  -- Bosnia & Herzegovina
  ('BIH','Nikola Vasilj','GK',1,'SK Austria Klagenfurt'),
  ('BIH','Ibrahim Šehić','GK',12,'Ferencváros'),
  ('BIH','Marko Dmitrović','GK',23,'Sevilla'),
  ('BIH','Sead Kolašinac','DEF',5,'Atalanta'),
  ('BIH','Ermin Bičakčić','DEF',3,'Leverkusen→free'),
  ('BIH','Amar Dedić','DEF',2,'RB Salzburg'),
  ('BIH','Vedad Hodžić','DEF',4,'NK Osijek'),
  ('BIH','Dario Šimić','DEF',16,'Nice'),
  ('BIH','Denis Huseinbašić','MID',8,'Köln'),
  ('BIH','Miralem Pjanić','MID',6,'Sharjah'),
  ('BIH','Armin Gigović','MID',14,'Borussia Mönchengladbach'),
  ('BIH','Haris Hajradinović','MID',10,'Domžale'),
  ('BIH','Kenan Kodro','FWD',11,'Málaga'),
  ('BIH','Edin Džeko','FWD',9,'Fenerbahçe'),
  ('BIH','Amer Gojak','MID',17,'Trabzonspor'),
  ('BIH','Ajdin Hasić','FWD',21,'Angers'),
  ('BIH','Ognjen Todorović','DEF',15,'VfL Bochum'),
  ('BIH','Adnan Kovačević','MID',18,'VfL Bochum'),
  ('BIH','Dejan Joveljić','FWD',7,'Sporting CP'),

  -- Qatar
  ('QAT','Meshaal Barsham','GK',1,'Al-Sadd'),
  ('QAT','Yousef Hassan','GK',21,'Al-Gharafa'),
  ('QAT','Sami Al-Hamadani','GK',16,'Al-Duhail'),
  ('QAT','Pedro Miguel','DEF',3,'Al-Sadd'),
  ('QAT','Abdelkarim Hassan','DEF',12,'Al-Sadd'),
  ('QAT','Tarek Salman','DEF',5,'Al-Sadd'),
  ('QAT','Bassam Al-Rawi','DEF',4,'Al-Duhail'),
  ('QAT','Mohammed Waad','DEF',14,'Al-Rayyan'),
  ('QAT','Assim Madibo','MID',6,'Al-Duhail'),
  ('QAT','Karim Boudiaf','MID',8,'Al-Duhail'),
  ('QAT','Salem Al-Hajri','MID',15,'Al-Sadd'),
  ('QAT','Ismaeel Mohammad','MID',17,'Al-Sadd'),
  ('QAT','Akram Afif','FWD',11,'Al-Sadd'),
  ('QAT','Almoez Ali','FWD',19,'Al-Duhail'),
  ('QAT','Hassan Al-Haydos','MID',10,'Al-Sadd'),
  ('QAT','Jalmoud Hamid','FWD',9,'Al-Rayyan'),
  ('QAT','Ahmed Alaaeldin','FWD',7,'Al-Ahli'),

  -- Switzerland
  ('SUI','Yann Sommer','GK',1,'Inter Milan'),
  ('SUI','Gregor Kobel','GK',12,'Borussia Dortmund'),
  ('SUI','Philipp Köhn','GK',23,'Monaco'),
  ('SUI','Manuel Akanji','DEF',5,'Manchester City'),
  ('SUI','Nico Elvedi','DEF',3,'Borussia Mönchengladbach'),
  ('SUI','Ricardo Rodríguez','DEF',13,'Torino'),
  ('SUI','Fabian Schär','DEF',20,'Newcastle United'),
  ('SUI','Silvan Widmer','DEF',2,'Mainz'),
  ('SUI','Kevin Mbabu','DEF',22,'Fulham'),
  ('SUI','Granit Xhaka','MID',10,'Bayer Leverkusen'),
  ('SUI','Remo Freuler','MID',8,'Nottingham Forest'),
  ('SUI','Denis Zakaria','MID',16,'AS Monaco'),
  ('SUI','Fabian Frei','MID',14,'FC Basel'),
  ('SUI','Michel Aebischer','MID',11,'FC Basel'),
  ('SUI','Breel Embolo','FWD',7,'Monaco'),
  ('SUI','Ruben Vargas','FWD',19,'Augsburg'),
  ('SUI','Noah Okafor','FWD',9,'AC Milan'),
  ('SUI','Dan Ndoye','FWD',17,'Bologna'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP C: Brazil · Morocco · Haiti · Scotland
  -- ═══════════════════════════════════════════════════════════════════

  -- Brazil
  ('BRA','Alisson Becker','GK',1,'Liverpool'),
  ('BRA','Ederson','GK',23,'Manchester City'),
  ('BRA','Weverton','GK',12,'Palmeiras'),
  ('BRA','Marquinhos','DEF',5,'Paris Saint-Germain'),
  ('BRA','Éder Militão','DEF',3,'Real Madrid'),
  ('BRA','Danilo','DEF',2,'Juventus'),
  ('BRA','Alex Telles','DEF',6,'Sevilla'),
  ('BRA','Bremer','DEF',4,'Juventus'),
  ('BRA','Wendell','DEF',16,'Porto'),
  ('BRA','Lucas Paquetá','MID',10,'West Ham United'),
  ('BRA','Casemiro','MID',5,'Manchester United'),
  ('BRA','Bruno Guimarães','MID',17,'Newcastle United'),
  ('BRA','Gerson','MID',8,'Flamengo'),
  ('BRA','Andreas Pereira','MID',15,'Fulham'),
  ('BRA','Vinícius Júnior','FWD',7,'Real Madrid'),
  ('BRA','Rodrygo','FWD',11,'Real Madrid'),
  ('BRA','Raphinha','FWD',19,'FC Barcelona'),
  ('BRA','Endrick','FWD',9,'Real Madrid'),
  ('BRA','Gabriel Martinelli','FWD',11,'Arsenal'),
  ('BRA','Gabriel Jesus','FWD',9,'Arsenal'),

  -- Morocco
  ('MAR','Yassine Bounou','GK',1,'Al-Hilal'),
  ('MAR','Munir','GK',16,'Hajduk Split'),
  ('MAR','Ahmed Reda Tagnaouti','GK',12,'Wydad AC'),
  ('MAR','Achraf Hakimi','DEF',2,'Paris Saint-Germain'),
  ('MAR','Noussair Mazraoui','DEF',22,'Manchester United'),
  ('MAR','Romain Saïss','DEF',5,'Besiktas'),
  ('MAR','Nayef Aguerd','DEF',3,'West Ham United'),
  ('MAR','Yahia Attiyat Allah','DEF',14,'Wydad AC'),
  ('MAR','Adam Masina','DEF',16,'Udinese'),
  ('MAR','Sofyan Amrabat','MID',4,'Fiorentina'),
  ('MAR','Azzedine Ounahi','MID',8,'Marseille'),
  ('MAR','Selim Amallah','MID',13,'Standard Liège'),
  ('MAR','Bilal El Khannouss','MID',7,'Genk'),
  ('MAR','Brahim Díaz','MID',10,'Real Madrid'),
  ('MAR','Hakim Ziyech','FWD',17,'Galatasaray'),
  ('MAR','Youssef En-Nesyri','FWD',9,'Fenerbahçe'),
  ('MAR','Soufiane Rahimi','FWD',11,'Al-Ain'),
  ('MAR','Ayoub El Kaabi','FWD',19,'Olympiacos'),

  -- Haiti
  ('HAI','Josué Duverger','GK',1,'SC Bastia'),
  ('HAI','Jonathan Beauvois','GK',16,'Lausanne-Sport'),
  ('HAI','James Léon','GK',22,'Montreal'),
  ('HAI','Mechack Jérôme','DEF',3,'Portland Timbers'),
  ('HAI','Steeven Saba','DEF',4,'Raith Rovers'),
  ('HAI','Alexandre Mélosse','DEF',2,'FC Lorient'),
  ('HAI','Derrick Etienne','DEF',5,'Columbus Crew'),
  ('HAI','Kevin Lafrance','DEF',12,'Sochaux'),
  ('HAI','Wilde-Donald Guerrier','MID',8,'Guadalajara'),
  ('HAI','Karl Elis Brillant','MID',6,'Ionikos'),
  ('HAI','Romario Williams','MID',14,'Portmore United'),
  ('HAI','Etzer Mondesir','MID',10,'RWD Molenbeek'),
  ('HAI','Jessy Deminguard','MID',17,'Racing Louisville'),
  ('HAI','Frantzdy Pierrot','FWD',9,'Vancouver Whitecaps'),
  ('HAI','Duckens Nazon','FWD',7,'Pau FC'),
  ('HAI','Ronaldo Lauture','FWD',11,'Chicago Fire'),
  ('HAI','Réveil Tima','FWD',19,'ACS Sepsi OSK'),

  -- Scotland
  ('SCO','Angus Gunn','GK',1,'Norwich City'),
  ('SCO','Craig Gordon','GK',13,'Heart of Midlothian'),
  ('SCO','Liam Kelly','GK',12,'Coventry City'),
  ('SCO','Andrew Robertson','DEF',3,'Liverpool'),
  ('SCO','Kieran Tierney','DEF',15,'Arsenal'),
  ('SCO','Liam Cooper','DEF',5,'Leeds United'),
  ('SCO','Grant Hanley','DEF',6,'Norwich City'),
  ('SCO','Anthony Ralston','DEF',2,'Celtic'),
  ('SCO','Jack Hendry','DEF',4,'Al-Ettifaq'),
  ('SCO','Scott McTominay','MID',10,'Napoli'),
  ('SCO','John McGinn','MID',7,'Aston Villa'),
  ('SCO','Callum McGregor','MID',8,'Celtic'),
  ('SCO','Stuart Armstrong','MID',14,'Southampton'),
  ('SCO','Ryan Christie','MID',11,'Bournemouth'),
  ('SCO','Billy Gilmour','MID',17,'Napoli'),
  ('SCO','Che Adams','FWD',9,'Southampton'),
  ('SCO','Lyndon Dykes','FWD',20,'QPR'),
  ('SCO','Lawrence Shankland','FWD',21,'Heart of Midlothian'),
  ('SCO','Ryan Gauld','FWD',16,'Vancouver Whitecaps'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP D: USA · Paraguay · Australia · Türkiye
  -- ═══════════════════════════════════════════════════════════════════

  -- USA
  ('USA','Matt Turner','GK',1,'Crystal Palace'),
  ('USA','Patrick Schulte','GK',18,'Columbus Crew'),
  ('USA','Zack Steffen','GK',12,'Colorado Rapids'),
  ('USA','Sergino Dest','DEF',2,'AC Milan'),
  ('USA','Antonee Robinson','DEF',5,'Fulham'),
  ('USA','Miles Robinson','DEF',4,'Atlanta United'),
  ('USA','Walker Zimmerman','DEF',3,'Nashville SC'),
  ('USA','Joe Scally','DEF',17,'Borussia Mönchengladbach'),
  ('USA','Tim Ream','DEF',13,'Fulham'),
  ('USA','Weston McKennie','MID',8,'Juventus'),
  ('USA','Tyler Adams','MID',4,'Bournemouth'),
  ('USA','Yunus Musah','MID',6,'AC Milan'),
  ('USA','Gio Reyna','MID',7,'Nottingham Forest'),
  ('USA','Luca de la Torre','MID',9,'Celta Vigo'),
  ('USA','Christian Pulisic','FWD',10,'AC Milan'),
  ('USA','Tim Weah','FWD',11,'Juventus'),
  ('USA','Ricardo Pepi','FWD',9,'PSV Eindhoven'),
  ('USA','Josh Sargent','FWD',22,'Norwich City'),
  ('USA','Folarin Balogun','FWD',15,'Crystal Palace'),

  -- Paraguay
  ('PAR','Antony Silva','GK',1,'Olimpia'),
  ('PAR','Anthony Servín','GK',23,'Nacional'),
  ('PAR','Alfredo Aguilar','GK',12,'Cerro Porteño'),
  ('PAR','Gustavo Gómez','DEF',3,'Palmeiras'),
  ('PAR','Omar Alderete','DEF',4,'Getafe'),
  ('PAR','Júnior Alonso','DEF',5,'Atlético Mineiro'),
  ('PAR','Santiago Arzamendia','DEF',16,'Cádiz'),
  ('PAR','Robert Rojas','DEF',2,'River Plate'),
  ('PAR','Alberto Espínola','DEF',14,'Olimpia'),
  ('PAR','Miguel Almirón','MID',10,'Newcastle United'),
  ('PAR','Mathías Villasanti','MID',8,'Grêmio'),
  ('PAR','Richard Sánchez','MID',6,'América'),
  ('PAR','Ángel Romero','MID',7,'Olimpia'),
  ('PAR','Andrés Cubas','MID',13,'Nantes'),
  ('PAR','Antonio Sanabria','FWD',9,'Torino'),
  ('PAR','Alexis Duarte','FWD',11,'Club Nacional'),
  ('PAR','Julio Enciso','FWD',22,'Brighton'),
  ('PAR','Gabriel Ávalos','FWD',19,'Olimpia'),

  -- Australia
  ('AUS','Mat Ryan','GK',1,'Real Sociedad'),
  ('AUS','Danny Vukovic','GK',18,'Central Coast Mariners'),
  ('AUS','Andrew Redmayne','GK',12,'Sydney FC'),
  ('AUS','Harry Souttar','DEF',3,'Leicester City'),
  ('AUS','Miloš Degenek','DEF',5,'Columbus Crew'),
  ('AUS','Bailey Wright','DEF',6,'Sunderland'),
  ('AUS','Aziz Behich','DEF',16,'Dundee United'),
  ('AUS','Nathaniel Atkinson','DEF',2,'Heart of Midlothian'),
  ('AUS','Fran Karačić','DEF',20,'Brescia'),
  ('AUS','Jackson Irvine','MID',8,'St. Pauli'),
  ('AUS','Ajdin Hrustić','MID',6,'Genoa'),
  ('AUS','Riley McGree','MID',10,'Middlesbrough'),
  ('AUS','Aaron Mooy','MID',13,'Celtic'),
  ('AUS','Cameron Devlin','MID',14,'Heart of Midlothian'),
  ('AUS','Mitch Duke','FWD',9,'Fagiano Okayama'),
  ('AUS','Martin Boyle','FWD',7,'Hibernian'),
  ('AUS','Jason Cummings','FWD',11,'Central Coast Mariners'),
  ('AUS','Garang Kuol','FWD',19,'Newcastle United'),

  -- Türkiye
  ('TUR','Altay Bayındır','GK',1,'Manchester United'),
  ('TUR','Uğurcan Çakır','GK',12,'Trabzonspor'),
  ('TUR','Mert Günok','GK',23,'Beşiktaş'),
  ('TUR','Merih Demiral','DEF',3,'Al-Ahli'),
  ('TUR','Zeki Çelik','DEF',2,'AS Roma'),
  ('TUR','Samet Akaydın','DEF',5,'Fenerbahçe'),
  ('TUR','Çağlar Söyüncü','DEF',4,'Atlético Madrid'),
  ('TUR','Ferdi Kadıoğlu','DEF',13,'Fenerbahçe'),
  ('TUR','Mert Müldür','DEF',17,'Sassuolo'),
  ('TUR','Hakan Çalhanoğlu','MID',10,'Inter Milan'),
  ('TUR','Salih Özcan','MID',6,'Borussia Dortmund'),
  ('TUR','Okay Yokuşlu','MID',8,'West Brom'),
  ('TUR','Arda Güler','MID',11,'Real Madrid'),
  ('TUR','Kenan Yıldız','MID',7,'Juventus'),
  ('TUR','Berk Celik','MID',14,'Fenerbahçe'),
  ('TUR','Cenk Tosun','FWD',9,'Beşiktaş'),
  ('TUR','Kaan Ayhan','DEF',15,'Galatasaray'),
  ('TUR','Barış Alper Yılmaz','FWD',19,'Galatasaray'),
  ('TUR','Halil Dervişoğlu','FWD',21,'Galatasaray'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP E: Germany · Curaçao · Ivory Coast · Ecuador
  -- ═══════════════════════════════════════════════════════════════════

  -- Germany
  ('GER','Manuel Neuer','GK',1,'Bayern Munich'),
  ('GER','Marc-André ter Stegen','GK',22,'FC Barcelona'),
  ('GER','Oliver Baumann','GK',12,'TSG Hoffenheim'),
  ('GER','Antonio Rüdiger','DEF',2,'Real Madrid'),
  ('GER','David Raum','DEF',5,'RB Leipzig'),
  ('GER','Benjamin Henrichs','DEF',15,'RB Leipzig'),
  ('GER','Nico Schlotterbeck','DEF',3,'Borussia Dortmund'),
  ('GER','Robin Koch','DEF',4,'Eintracht Frankfurt'),
  ('GER','Thilo Kehrer','DEF',13,'West Ham United'),
  ('GER','Joshua Kimmich','MID',6,'Bayern Munich'),
  ('GER','Toni Kroos','MID',8,'Real Madrid'),
  ('GER','Leroy Sané','MID',19,'Bayern Munich'),
  ('GER','Thomas Müller','MID',13,'Bayern Munich'),
  ('GER','Florian Wirtz','MID',10,'Bayer Leverkusen'),
  ('GER','Ilkay Gündoğan','MID',21,'FC Barcelona'),
  ('GER','Jamal Musiala','FWD',7,'Bayern Munich'),
  ('GER','Niclas Füllkrug','FWD',9,'West Ham United'),
  ('GER','Kai Havertz','FWD',11,'Arsenal'),
  ('GER','Serge Gnabry','FWD',17,'Bayern Munich'),

  -- Curaçao
  ('CUW','Eloy Room','GK',1,'Columbus Crew'),
  ('CUW','Wuilker Faríñez','GK',12,'Millonarios'),
  ('CUW','Sven Orie','GK',23,'SC Heerenveen'),
  ('CUW','Cuco Martina','DEF',2,'unattached'),
  ('CUW','Etienne Reijnen','DEF',4,'FC Emmen'),
  ('CUW','Rajiv van La Parra','DEF',3,'Middlesbrough'),
  ('CUW','Genaro Snijders','DEF',5,'Heracles'),
  ('CUW','Roshon van der Veen','DEF',16,'VVV-Venlo'),
  ('CUW','Leandro Bacuna','MID',8,'Cardiff City'),
  ('CUW','Giliano Wijnaldum','MID',10,'Sparta Rotterdam'),
  ('CUW','Jurickson Profar','MID',7,'San Diego Padres'),
  ('CUW','Quiñero Blanco','MID',14,'Deportivo Cali'),
  ('CUW','Gevaro Nepomuceno','MID',11,'Aris Thessaloniki'),
  ('CUW','Jarchinio Antonia','FWD',9,'ADO Den Haag'),
  ('CUW','Darryl Lachman','DEF',6,'Sparta Rotterdam'),
  ('CUW','Chadrick Akolo','FWD',19,'Metz'),
  ('CUW','Sheraldo Becker','FWD',17,'Union Berlin'),

  -- Ivory Coast
  ('CIV','Yahia Fofana','GK',1,'Leicester City'),
  ('CIV','Badra Ali Sangaré','GK',16,'ASEC Mimosas'),
  ('CIV','Sylvain Gbohouo','GK',23,'Mamelodi Sundowns'),
  ('CIV','Serge Aurier','DEF',2,'unattached'),
  ('CIV','Willy Boly','DEF',5,'Nottingham Forest'),
  ('CIV','Odilon Kossounou','DEF',3,'Bayer Leverkusen'),
  ('CIV','Simon Deli','DEF',4,'Club Brugge'),
  ('CIV','Ghislain Konan','DEF',15,'Nancy'),
  ('CIV','Franck Kessié','MID',6,'FC Barcelona'),
  ('CIV','Jean-Michaël Seri','MID',8,'Fulham'),
  ('CIV','Ibrahim Sangaré','MID',19,'Nottingham Forest'),
  ('CIV','Max Gradel','MID',7,'Toulouse'),
  ('CIV','Sébastien Haller','FWD',9,'Borussia Dortmund'),
  ('CIV','Wilfried Zaha','FWD',11,'Galatasaray'),
  ('CIV','Nicolas Pépé','FWD',19,'RC Lens'),
  ('CIV','Simon Adingra','FWD',17,'Brighton'),
  ('CIV','Jonathan Kodjia','FWD',10,'Al-Gharafa'),

  -- Ecuador
  ('ECU','Hernán Galíndez','GK',1,'Aucas'),
  ('ECU','Alexander Domínguez','GK',12,'LDU Quito'),
  ('ECU','Wellington Ramírez','GK',23,'Independiente del Valle'),
  ('ECU','Pervis Estupiñán','DEF',3,'Brighton'),
  ('ECU','Piero Hincapié','DEF',12,'Bayer Leverkusen'),
  ('ECU','Robert Arboleda','DEF',4,'São Paulo'),
  ('ECU','Xavier Arreaga','DEF',5,'Seattle Sounders'),
  ('ECU','Angelo Preciado','DEF',2,'Genk'),
  ('ECU','Diego Palacios','DEF',15,'LAFC'),
  ('ECU','Moisés Caicedo','MID',10,'Chelsea'),
  ('ECU','Carlos Gruezo','MID',8,'FC Augsburg'),
  ('ECU','Jhegson Méndez','MID',6,'LAFC'),
  ('ECU','Romario Ibarra','MID',19,'Quito'),
  ('ECU','Jeremy Sarmiento','MID',11,'Brighton'),
  ('ECU','Enner Valencia','FWD',13,'Inter Miami'),
  ('ECU','Felipe Caicedo','FWD',21,'Independiente'),
  ('ECU','Michael Estrada','FWD',9,'Cruz Azul'),
  ('ECU','Gonzalo Plata','FWD',7,'Al-Qadsiah'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP F: Netherlands · Japan · Sweden · Tunisia
  -- ═══════════════════════════════════════════════════════════════════

  -- Netherlands
  ('NED','Bart Verbruggen','GK',1,'Brighton'),
  ('NED','Mark Flekken','GK',12,'Brentford'),
  ('NED','Justin Bijlow','GK',22,'Feyenoord'),
  ('NED','Virgil van Dijk','DEF',4,'Liverpool'),
  ('NED','Matthijs de Ligt','DEF',3,'Manchester United'),
  ('NED','Nathan Aké','DEF',5,'Manchester City'),
  ('NED','Denzel Dumfries','DEF',2,'Inter Milan'),
  ('NED','Jurriën Timber','DEF',12,'Arsenal'),
  ('NED','Daley Blind','DEF',17,'Girona'),
  ('NED','Frenkie de Jong','MID',21,'FC Barcelona'),
  ('NED','Teun Koopmeiners','MID',8,'Juventus'),
  ('NED','Ryan Gravenberch','MID',7,'Liverpool'),
  ('NED','Xavi Simons','MID',10,'PSG/RB Leipzig'),
  ('NED','Tijjani Reijnders','MID',14,'AC Milan'),
  ('NED','Cody Gakpo','FWD',11,'Liverpool'),
  ('NED','Memphis Depay','FWD',10,'Atlético Madrid'),
  ('NED','Wout Weghorst','FWD',19,'TSG Hoffenheim'),
  ('NED','Donyell Malen','FWD',9,'Aston Villa'),

  -- Japan
  ('JPN','Shuichi Gonda','GK',1,'Shimizu S-Pulse'),
  ('JPN','Daniel Schmidt','GK',12,'Sint-Truiden'),
  ('JPN','Zion Suzuki','GK',23,'Sint-Truiden'),
  ('JPN','Maya Yoshida','DEF',22,'Vissel Kobe'),
  ('JPN','Yuto Nagatomo','DEF',5,'unattached'),
  ('JPN','Ko Itakura','DEF',3,'Borussia Mönchengladbach'),
  ('JPN','Hiroki Sakai','DEF',2,'Urawa Red Diamonds'),
  ('JPN','Takehiro Tomiyasu','DEF',6,'Arsenal'),
  ('JPN','Shogo Taniguchi','DEF',4,'Kawasaki Frontale'),
  ('JPN','Wataru Endo','MID',17,'Liverpool'),
  ('JPN','Gaku Shibasaki','MID',8,'Getafe'),
  ('JPN','Hidemasa Morita','MID',14,'Sporting CP'),
  ('JPN','Daichi Kamada','MID',10,'Crystal Palace'),
  ('JPN','Junya Ito','MID',9,'Reims'),
  ('JPN','Kaoru Mitoma','FWD',11,'Brighton'),
  ('JPN','Takefusa Kubo','FWD',7,'Real Sociedad'),
  ('JPN','Ayase Ueda','FWD',18,'Feyenoord'),
  ('JPN','Ritsu Doan','FWD',8,'SC Freiburg'),

  -- Sweden
  ('SWE','Robin Olsen','GK',1,'Aston Villa'),
  ('SWE','Kristoffer Nordfeldt','GK',12,'Gençlerbirliği'),
  ('SWE','Samuel Brolin','GK',23,'IFK Göteborg'),
  ('SWE','Victor Lindelöf','DEF',2,'Manchester United'),
  ('SWE','Ludwig Augustinsson','DEF',3,'unattached'),
  ('SWE','Pontus Jansson','DEF',4,'Brentford'),
  ('SWE','Carl Starfelt','DEF',5,'Southampton'),
  ('SWE','Emil Krafth','DEF',16,'Newcastle United'),
  ('SWE','Mikael Lustig','DEF',17,'AIK'),
  ('SWE','Dejan Kulusevski','MID',21,'Tottenham Hotspur'),
  ('SWE','Albin Ekdal','MID',8,'Spezia'),
  ('SWE','Gustav Svensson','MID',6,'Club de Foot Montréal'),
  ('SWE','Mattias Svanberg','MID',14,'Wolfsburg'),
  ('SWE','Samuel Dahl','DEF',15,'Borussia Dortmund'),
  ('SWE','Alexander Isak','FWD',11,'Newcastle United'),
  ('SWE','Viktor Gyökeres','FWD',9,'Sporting CP'),
  ('SWE','Robin Quaison','FWD',7,'unattached'),
  ('SWE','Jordan Larsson','FWD',10,'Spartak Moscow'),

  -- Tunisia
  ('TUN','Aymen Dahmen','GK',1,'Stade Tunisien'),
  ('TUN','Mouez Hassen','GK',16,'Club Africain'),
  ('TUN','Farouk Ben Mustapha','GK',23,'Al-Faisaly'),
  ('TUN','Dylan Bronn','DEF',5,'Salernitana'),
  ('TUN','Montassar Talbi','DEF',3,'Lorient'),
  ('TUN','Wajdi Kechrida','DEF',2,'Trabzonspor'),
  ('TUN','Nader Ghandri','DEF',4,'Nottingham Forest'),
  ('TUN','Ali Abdi','DEF',17,'Valenciennes'),
  ('TUN','Aïssa Laïdouni','MID',6,'Ferencváros'),
  ('TUN','Ellyes Skhiri','MID',8,'Eintracht Frankfurt'),
  ('TUN','Youssef Msakni','FWD',11,'Al-Arabi'),
  ('TUN','Khazri Wahbi','MID',10,'Montpellier'),
  ('TUN','Mohamed Ben Romdhane','MID',14,'Kasımpaşa'),
  ('TUN','Seifeddine Jaziri','FWD',9,'Umm Salal'),
  ('TUN','Naïm Sliti','FWD',7,'Umm Salal'),
  ('TUN','Hamza Rafia','MID',19,'ESTAC Troyes'),
  ('TUN','Ghaylen Chaalali','MID',20,'Espérance Tunis'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP G: Belgium · Egypt · Iran · New Zealand
  -- ═══════════════════════════════════════════════════════════════════

  -- Belgium
  ('BEL','Thibaut Courtois','GK',1,'Real Madrid'),
  ('BEL','Koen Casteels','GK',12,'Wolfsburg'),
  ('BEL','Matz Sels','GK',23,'Nottingham Forest'),
  ('BEL','Toby Alderweireld','DEF',2,'Royal Antwerp'),
  ('BEL','Jan Vertonghen','DEF',5,'Anderlecht'),
  ('BEL','Thomas Meunier','DEF',15,'Club Brugge'),
  ('BEL','Timothy Castagne','DEF',3,'Fulham'),
  ('BEL','Arthur Theate','DEF',4,'Rennes'),
  ('BEL','Wout Faes','DEF',13,'Leicester City'),
  ('BEL','Kevin De Bruyne','MID',7,'Manchester City'),
  ('BEL','Axel Witsel','MID',6,'Atlético Madrid'),
  ('BEL','Leander Dendoncker','MID',8,'Aston Villa'),
  ('BEL','Hans Vanaken','MID',14,'Club Brugge'),
  ('BEL','Youri Tielemans','MID',10,'Aston Villa'),
  ('BEL','Romelu Lukaku','FWD',9,'AS Roma'),
  ('BEL','Jérémy Doku','FWD',11,'Manchester City'),
  ('BEL','Dodi Lukébakio','FWD',17,'Sevilla'),
  ('BEL','Loïs Openda','FWD',15,'RB Leipzig'),

  -- Egypt
  ('EGY','Mohamed El-Shennawy','GK',1,'Al-Ahly'),
  ('EGY','Gabaski','GK',16,'Zamalek'),
  ('EGY','Ibrahim Adel','GK',23,'Pyramids FC'),
  ('EGY','Ahmed Hegazi','DEF',5,'Al-Ittihad'),
  ('EGY','Mohamed Abdelmonem','DEF',3,'Al-Ahly'),
  ('EGY','Karim Hafez','DEF',4,'Pyramids FC'),
  ('EGY','Akram Tawfik','DEF',2,'Al-Ahly'),
  ('EGY','Ahmed El-Fotouh','DEF',17,'Zamalek'),
  ('EGY','Amr El-Sulaya','DEF',14,'Al-Ahly'),
  ('EGY','Tarek Hamed','MID',6,'Zamalek'),
  ('EGY','Ahmed Sayed "Zizo"','MID',10,'Al-Ittihad'),
  ('EGY','Emam Ashour','MID',8,'Zamalek'),
  ('EGY','Mahmoud "Trezeguet"','MID',11,'Istanbul Başakşehir'),
  ('EGY','Mustafa Mohamed','FWD',22,'Galatasaray'),
  ('EGY','Mohamed Salah','FWD',10,'Liverpool'),
  ('EGY','Omar Marmoush','FWD',9,'Manchester City'),
  ('EGY','Marwan Hamdy','FWD',17,'Pyramids FC'),

  -- Iran
  ('IRN','Alireza Beiranvand','GK',1,'Antwerp'),
  ('IRN','Hossein Hosseini','GK',12,'Persepolis'),
  ('IRN','Payam Niazmand','GK',23,'Sepahan'),
  ('IRN','Ehsan Hajsafi','DEF',3,'AEK Athens'),
  ('IRN','Majid Hosseini','DEF',4,'Kasımpaşa'),
  ('IRN','Shojae Khalilzadeh','DEF',5,'Al-Qadsiah'),
  ('IRN','Sadegh Moharrami','DEF',2,'Dynamo Zagreb'),
  ('IRN','Milad Mohammadi','DEF',16,'Ferencváros'),
  ('IRN','Aref Gholami','DEF',17,'Persepolis'),
  ('IRN','Saeid Ezatolahi','MID',8,'Vejle BK'),
  ('IRN','Alireza Jahanbakhsh','MID',11,'Feyenoord'),
  ('IRN','Vahid Amiri','MID',14,'Persepolis'),
  ('IRN','Ali Gholizadeh','MID',7,'Charleroi'),
  ('IRN','Ahmad Noorollahi','MID',6,'Kayserispor'),
  ('IRN','Mehdi Taremi','FWD',9,'Inter Milan'),
  ('IRN','Sardar Azmoun','FWD',19,'Bayer Leverkusen'),
  ('IRN','Karim Ansarifard','FWD',10,'Omonia'),
  ('IRN','Allahyar Sayyadmanesh','FWD',17,'Erzurumspor'),

  -- New Zealand
  ('NZL','Stefan Marinovic','GK',1,'Vancouver Whitecaps'),
  ('NZL','Michael Woud','GK',12,'Fortuna Sittard'),
  ('NZL','James Penney','GK',22,'Eastern Suburbs'),
  ('NZL','Winston Reid','DEF',5,'Brentford'),
  ('NZL','Tommy Smith','DEF',2,'Stoke City'),
  ('NZL','Liberato Cacace','DEF',3,'Southampton'),
  ('NZL','Tim Payne','DEF',4,'Sacramento Republic'),
  ('NZL','Nando Pijnaker','DEF',6,'Groningen'),
  ('NZL','Clayton Lewis','MID',8,'AZ Alkmaar'),
  ('NZL','Alex Greive','MID',11,'Auckland City'),
  ('NZL','Joe Bell','MID',6,'Columbus Crew'),
  ('NZL','Elijah Just','MID',14,'Midtjylland'),
  ('NZL','Marko Stamenic','MID',10,'Colorado Rapids'),
  ('NZL','Chris Wood','FWD',9,'Nottingham Forest'),
  ('NZL','Callan Elliot','FWD',7,'Wellington Phoenix'),
  ('NZL','Matthew Garbett','FWD',17,'Wellington Phoenix'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP H: Spain · Cape Verde · Saudi Arabia · Uruguay
  -- ═══════════════════════════════════════════════════════════════════

  -- Spain
  ('ESP','David Raya','GK',1,'Arsenal'),
  ('ESP','Unai Simón','GK',23,'Athletic Bilbao'),
  ('ESP','Álex Remiro','GK',13,'Real Sociedad'),
  ('ESP','Dani Carvajal','DEF',2,'Real Madrid'),
  ('ESP','Alejandro Grimaldo','DEF',3,'Bayer Leverkusen'),
  ('ESP','Pau Cubarsí','DEF',4,'FC Barcelona'),
  ('ESP','Aymeric Laporte','DEF',14,'Al-Nassr'),
  ('ESP','Robin Le Normand','DEF',5,'Atlético Madrid'),
  ('ESP','Dani Olmo','MID',8,'RB Leipzig'),
  ('ESP','Rodri','MID',16,'Manchester City'),
  ('ESP','Pedri','MID',6,'FC Barcelona'),
  ('ESP','Fabián Ruiz','MID',18,'Paris Saint-Germain'),
  ('ESP','Mikel Merino','MID',10,'Arsenal'),
  ('ESP','Lamine Yamal','FWD',19,'FC Barcelona'),
  ('ESP','Nico Williams','FWD',11,'Athletic Bilbao'),
  ('ESP','Álvaro Morata','FWD',7,'AC Milan'),
  ('ESP','Mikel Oyarzabal','FWD',9,'Real Sociedad'),
  ('ESP','Ferran Torres','FWD',21,'FC Barcelona'),
  ('ESP','Joselu','FWD',17,'Real Madrid'),

  -- Cape Verde
  ('CPV','Vozinha','GK',1,'SC Covilhã'),
  ('CPV','Carlos Batalha','GK',12,'Lusitânia'),
  ('CPV','Brayan Garçia','GK',23,'Sporting CP B'),
  ('CPV','Roberto Lopes','DEF',4,'Shamrock Rovers'),
  ('CPV','Stopira','DEF',3,'Hansa Rostock'),
  ('CPV','Logan Costa','DEF',5,'Toulouse'),
  ('CPV','Diney','DEF',2,'Sporting CP'),
  ('CPV','Willy Semedo','DEF',14,'SC Braga'),
  ('CPV','Ryan Mendes','MID',11,'Hatayspor'),
  ('CPV','Garry Rodrigues','FWD',7,'Al-Adalah'),
  ('CPV','Kenny Rocha Santos','MID',8,'Casa Pia'),
  ('CPV','Fali Candé','MID',6,'Vitória de Guimarães'),
  ('CPV','Kelvin','FWD',9,'Sporting CP'),
  ('CPV','Bryan Tavares','MID',17,'Feirense'),
  ('CPV','Hélder Djaló','MID',10,'Sporting CP'),
  ('CPV','Jamiro Monteiro','MID',21,'DC United'),
  ('CPV','Jordan','FWD',19,'Sporting CP B'),

  -- Saudi Arabia
  ('KSA','Mohammed Al-Owais','GK',21,'Al-Hilal'),
  ('KSA','Fawaz Al-Qarni','GK',1,'Al-Ahli'),
  ('KSA','Sultan Al-Ghannam','GK',12,'Al-Ittihad'),
  ('KSA','Saud Abdulhamid','DEF',2,'AS Roma'),
  ('KSA','Ali Al-Bulaihi','DEF',5,'Al-Hilal'),
  ('KSA','Hassan Tambakti','DEF',3,'Al-Hilal'),
  ('KSA','Sultan Al-Ghanam','DEF',4,'Al-Ahli'),
  ('KSA','Yasser Al-Shahrani','DEF',13,'Al-Hilal'),
  ('KSA','Abdulelah Al-Amri','DEF',16,'Al-Shabab'),
  ('KSA','Salman Al-Faraj','MID',8,'Al-Hilal'),
  ('KSA','Mohamed Kanno','MID',6,'Al-Hilal'),
  ('KSA','Riyadh Sharahili','MID',17,'Al-Hilal'),
  ('KSA','Sami Al-Najei','MID',14,'Al-Shabab'),
  ('KSA','Ali Al-Hassan','MID',11,'Rayo Vallecano'),
  ('KSA','Salem Al-Dawsari','FWD',10,'Al-Hilal'),
  ('KSA','Firas Al-Buraikan','FWD',9,'Al-Fateh'),
  ('KSA','Haitham Asiri','FWD',7,'Al-Ahli'),
  ('KSA','Muhannad Al-Shanqiti','FWD',19,'Al-Qadsiah'),

  -- Uruguay
  ('URU','Sergio Rochet','GK',1,'Club Nacional'),
  ('URU','Sebastián Sosa','GK',12,'Independiente'),
  ('URU','Guillermo De Amores','GK',23,'Club Nacional'),
  ('URU','Ronald Araújo','DEF',2,'FC Barcelona'),
  ('URU','José María Giménez','DEF',3,'Atlético Madrid'),
  ('URU','Diego Godín','DEF',3,'Club Nacional'),
  ('URU','Sebastián Coates','DEF',4,'Sporting CP'),
  ('URU','Matías Viña','DEF',16,'AS Roma'),
  ('URU','José Luis Rodríguez','DEF',22,'Young Boys'),
  ('URU','Federico Valverde','MID',8,'Real Madrid'),
  ('URU','Rodrigo Bentancur','MID',6,'Tottenham Hotspur'),
  ('URU','Nicolás de la Cruz','MID',14,'River Plate'),
  ('URU','Giorgian De Arrascaeta','MID',10,'Flamengo'),
  ('URU','Facundo Pellistri','MID',7,'Manchester United'),
  ('URU','Darwin Núñez','FWD',9,'Liverpool'),
  ('URU','Luis Suárez','FWD',9,'Grêmio'),
  ('URU','Edinson Cavani','FWD',21,'Valencia'),
  ('URU','Maximiliano Araújo','FWD',19,'Sporting CP'),
  ('URU','Brian Rodríguez','FWD',17,'LAFC'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP I: France · Senegal · Iraq · Norway
  -- ═══════════════════════════════════════════════════════════════════

  -- France
  ('FRA','Mike Maignan','GK',1,'AC Milan'),
  ('FRA','Brice Samba','GK',16,'RC Lens'),
  ('FRA','Alphonse Areola','GK',12,'West Ham United'),
  ('FRA','William Saliba','DEF',4,'Arsenal'),
  ('FRA','Dayot Upamecano','DEF',5,'Bayern Munich'),
  ('FRA','Théo Hernández','DEF',22,'AC Milan'),
  ('FRA','Benjamin Pavard','DEF',2,'Inter Milan'),
  ('FRA','Jules Koundé','DEF',3,'FC Barcelona'),
  ('FRA','Ibrahima Konaté','DEF',5,'Liverpool'),
  ('FRA','Aurélien Tchouaméni','MID',14,'Real Madrid'),
  ('FRA','Adrien Rabiot','MID',8,'Juventus'),
  ('FRA','Eduardo Camavinga','MID',10,'Real Madrid'),
  ('FRA','Mattéo Guendouzi','MID',6,'Lazio'),
  ('FRA','Warren Zaïre-Emery','MID',17,'Paris Saint-Germain'),
  ('FRA','Kylian Mbappé','FWD',10,'Real Madrid'),
  ('FRA','Ousmane Dembélé','FWD',11,'Paris Saint-Germain'),
  ('FRA','Marcus Thuram','FWD',9,'Inter Milan'),
  ('FRA','Randal Kolo Muani','FWD',7,'Juventus'),
  ('FRA','Kingsley Coman','FWD',11,'Bayern Munich'),

  -- Senegal
  ('SEN','Édouard Mendy','GK',1,'Al-Ahli'),
  ('SEN','Alfred Gomis','GK',16,'Rennes'),
  ('SEN','Seny Dieng','GK',23,'Middlesbrough'),
  ('SEN','Kalidou Koulibaly','DEF',3,'Al-Hilal'),
  ('SEN','Abdou Diallo','DEF',5,'RB Leipzig'),
  ('SEN','Youssouf Sabaly','DEF',2,'Real Betis'),
  ('SEN','Fodé Ballo-Touré','DEF',23,'AC Milan'),
  ('SEN','Moussa Ndiaye','DEF',4,'Nice'),
  ('SEN','Ismaila Sarr','MID',7,'Crystal Palace'),
  ('SEN','Idrissa Gueye','MID',6,'Everton'),
  ('SEN','Pape Matar Sarr','MID',14,'Tottenham Hotspur'),
  ('SEN','Nampalys Mendy','MID',8,'Leicester City'),
  ('SEN','Krepin Diatta','MID',11,'Monaco'),
  ('SEN','Sadio Mané','FWD',10,'Al-Nassr'),
  ('SEN','Nicolas Jackson','FWD',9,'Chelsea'),
  ('SEN','Bamba Dieng','FWD',13,'OGC Nice'),
  ('SEN','Habib Diallo','FWD',19,'RC Strasbourg'),

  -- Iraq
  ('IRQ','Jalal Hassan','GK',1,'Air Force Club'),
  ('IRQ','Mohamed Hameed','GK',12,'Al-Shorta'),
  ('IRQ','Dhurgham Ismail','GK',23,'Al-Zawraa'),
  ('IRQ','Ahmad Ibrahim','DEF',5,'Al-Shorta'),
  ('IRQ','Ali Adnan','DEF',3,'unattached'),
  ('IRQ','Rebin Sulaka','DEF',4,'Sivasspor'),
  ('IRQ','Saman Shaker','DEF',2,'Zamalek'),
  ('IRQ','Hammadi Ahmed','DEF',14,'Al-Zawraa'),
  ('IRQ','Abdul-Hussein Al-Saedi','MID',6,'Air Force Club'),
  ('IRQ','Bashar Resan','MID',7,'Al-Shorta'),
  ('IRQ','Ali Faez','MID',10,'Göztepe'),
  ('IRQ','Hussain Ali','MID',8,'Al-Zawraa'),
  ('IRQ','Amjad Attwan','MID',11,'Al-Karkh'),
  ('IRQ','Aymen Hussein','FWD',9,'Ferencváros'),
  ('IRQ','Alaa Abbas','FWD',17,'Al-Shorta'),
  ('IRQ','Mohanad Ali','FWD',19,'Hatta Club'),
  ('IRQ','Murtada Jabbar','FWD',21,'Vitesse'),

  -- Norway
  ('NOR','Ørjan Nyland','GK',1,'Brentford'),
  ('NOR','Rune Jarstein','GK',12,'Hertha BSC'),
  ('NOR','Sondre Rossbach','GK',23,'Djurgårdens'),
  ('NOR','Kristoffer Ajer','DEF',2,'Brentford'),
  ('NOR','Leo Skiri Østigård','DEF',5,'Napoli'),
  ('NOR','Andreas Hanche-Olsen','DEF',3,'Mainz'),
  ('NOR','Omar Elabdellaoui','DEF',4,'Galatasaray'),
  ('NOR','Birger Meling','DEF',16,'Rennes'),
  ('NOR','Stian Gregersen','DEF',15,'Marseille'),
  ('NOR','Martin Ødegaard','MID',8,'Arsenal'),
  ('NOR','Sander Berge','MID',6,'Burnley'),
  ('NOR','Fredrik Aursnes','MID',14,'Benfica'),
  ('NOR','Mathias Normann','MID',17,'Standard Liège'),
  ('NOR','Morten Thorsby','MID',11,'Union Berlin'),
  ('NOR','Erling Haaland','FWD',9,'Manchester City'),
  ('NOR','Joshua King','FWD',7,'Watford'),
  ('NOR','Alexander Sørloth','FWD',10,'Real Sociedad'),
  ('NOR','Mohamed Elyounoussi','FWD',21,'Celtic'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP J: Argentina · Algeria · Austria · Jordan
  -- ═══════════════════════════════════════════════════════════════════

  -- Argentina
  ('ARG','Emiliano Martínez','GK',23,'Aston Villa'),
  ('ARG','Gerónimo Rulli','GK',1,'Ajax'),
  ('ARG','Franco Armani','GK',12,'River Plate'),
  ('ARG','Cristian Romero','DEF',13,'Tottenham Hotspur'),
  ('ARG','Lisandro Martínez','DEF',14,'Manchester United'),
  ('ARG','Nicolás Otamendi','DEF',19,'Benfica'),
  ('ARG','Nahuel Molina','DEF',26,'Atlético Madrid'),
  ('ARG','Nicolás Tagliafico','DEF',3,'Lyon'),
  ('ARG','Marcos Acuña','DEF',8,'Sevilla'),
  ('ARG','Rodrigo De Paul','MID',7,'Atlético Madrid'),
  ('ARG','Leandro Paredes','MID',5,'AS Roma'),
  ('ARG','Enzo Fernández','MID',24,'Chelsea'),
  ('ARG','Mac Allister','MID',20,'Liverpool'),
  ('ARG','Giovani Lo Celso','MID',18,'Villarreal'),
  ('ARG','Lionel Messi','FWD',10,'Inter Miami'),
  ('ARG','Julián Álvarez','FWD',9,'Atlético Madrid'),
  ('ARG','Lautaro Martínez','FWD',22,'Inter Milan'),
  ('ARG','Ángel Di María','FWD',11,'Benfica'),
  ('ARG','Paulo Dybala','FWD',21,'AS Roma'),

  -- Algeria
  ('ALG','Raïs M''Bolhi','GK',1,'Tlemcen'),
  ('ALG','Azzedine Doukha','GK',16,'Espérance Tunis'),
  ('ALG','Alexandre Oukidja','GK',23,'FC Metz'),
  ('ALG','Riyad Mahrez','FWD',7,'Al-Ahli'),
  ('ALG','Ismaël Bennacer','MID',8,'AC Milan'),
  ('ALG','Sofiane Feghouli','MID',10,'Galatasaray'),
  ('ALG','Aïssa Mandi','DEF',3,'Real Betis'),
  ('ALG','Djamel Benlamri','DEF',4,'Krasnodar'),
  ('ALG','Ramy Bensebaini','DEF',16,'Borussia Dortmund'),
  ('ALG','Mehdi Tahrat','DEF',2,'Sporting Charleroi'),
  ('ALG','Zineddine Ferhat','MID',11,'Nantes'),
  ('ALG','Bilal Benhamouda','MID',14,'Al-Qadsiah'),
  ('ALG','Said Benrahma','MID',22,'Lyon'),
  ('ALG','Houssem Aouar','MID',6,'Besiktas'),
  ('ALG','Baghdad Bounedjah','FWD',9,'Al-Sadd'),
  ('ALG','Andy Delort','FWD',21,'Nice'),
  ('ALG','Youcef Belaïli','FWD',17,'Aris Thessaloniki'),

  -- Austria
  ('AUT','Patrick Pentz','GK',1,'Bayer Leverkusen'),
  ('AUT','Heinz Lindner','GK',12,'Eintracht Frankfurt'),
  ('AUT','Alexander Schlager','GK',23,'LASK'),
  ('AUT','David Alaba','DEF',14,'Real Madrid'),
  ('AUT','Philipp Lienhart','DEF',3,'SC Freiburg'),
  ('AUT','Stefan Posch','DEF',5,'Bologna'),
  ('AUT','Maximilian Wöber','DEF',4,'Leeds United'),
  ('AUT','Gernot Trauner','DEF',2,'Feyenoord'),
  ('AUT','Christopher Trimmel','DEF',16,'Union Berlin'),
  ('AUT','Marcel Sabitzer','MID',7,'Borussia Dortmund'),
  ('AUT','Konrad Laimer','MID',17,'Bayern Munich'),
  ('AUT','Florian Grillitsch','MID',8,'Hoffenheim'),
  ('AUT','Christoph Baumgartner','MID',10,'RB Leipzig'),
  ('AUT','Nicolas Seiwald','MID',14,'RB Salzburg'),
  ('AUT','Marko Arnautović','FWD',9,'Inter Milan'),
  ('AUT','Michael Gregoritsch','FWD',19,'SC Freiburg'),
  ('AUT','Sasa Kalajdzic','FWD',21,'Wolfsburg'),
  ('AUT','Guido Burgstaller','FWD',11,'SK Rapid Wien'),

  -- Jordan
  ('JOR','Yazeed Abulaila','GK',1,'Al-Wehdat'),
  ('JOR','Muntasir Talal','GK',12,'Shabab Al-Ordon'),
  ('JOR','Mohammad Al-Shembari','GK',23,'Al-Faisaly'),
  ('JOR','Bachar Nafati','DEF',5,'Nantes'),
  ('JOR','Amer Shafi','DEF',3,'Al-Faisaly'),
  ('JOR','Yazan Naimat','DEF',4,'Shabab Al-Ordon'),
  ('JOR','Ahmad Nasib','DEF',2,'Al-Wehdat'),
  ('JOR','Anas Bani Yaseen','DEF',14,'Hapoel Tel Aviv'),
  ('JOR','Yazan Al-Arab','MID',8,'Vejle BK'),
  ('JOR','Baha' Faisal','MID',6,'Al-Ahly'),
  ('JOR','Hashem Abulaila','MID',10,'Al-Wahda'),
  ('JOR','Musa Al-Taamari','FWD',11,'Montpellier'),
  ('JOR','Mousa Al-Tamari','FWD',7,'Standard Liège'),
  ('JOR','Ahmad Thabt','FWD',9,'Al-Wehdat'),
  ('JOR','Shadi Abu Hashim','FWD',19,'Al-Faisaly'),
  ('JOR','Noor Al-Rawabdeh','MID',17,'Shabab Al-Ordon'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP K: Portugal · DR Congo · Uzbekistan · Colombia
  -- ═══════════════════════════════════════════════════════════════════

  -- Portugal
  ('POR','Diogo Costa','GK',1,'FC Porto'),
  ('POR','Rui Patrício','GK',22,'AS Roma'),
  ('POR','José Sá','GK',12,'Wolverhampton'),
  ('POR','Rúben Dias','DEF',3,'Manchester City'),
  ('POR','João Cancelo','DEF',20,'FC Barcelona'),
  ('POR','Nuno Mendes','DEF',19,'Paris Saint-Germain'),
  ('POR','Gonçalo Inácio','DEF',4,'Sporting CP'),
  ('POR','Diogo Dalot','DEF',2,'Manchester United'),
  ('POR','António Silva','DEF',14,'Benfica'),
  ('POR','Vitinha','MID',16,'Paris Saint-Germain'),
  ('POR','Bruno Fernandes','MID',8,'Manchester United'),
  ('POR','Bernardo Silva','MID',10,'Manchester City'),
  ('POR','João Palhinha','MID',26,'Bayern Munich'),
  ('POR','Otávio','MID',11,'Al-Nassr'),
  ('POR','Cristiano Ronaldo','FWD',7,'Al-Nassr'),
  ('POR','Rafael Leão','FWD',17,'AC Milan'),
  ('POR','Gonçalo Ramos','FWD',9,'Paris Saint-Germain'),
  ('POR','João Félix','FWD',11,'FC Barcelona'),
  ('POR','Pedro Neto','FWD',15,'Chelsea'),

  -- DR Congo
  ('COD','Joël Kiassumbua','GK',1,'Charleroi'),
  ('COD','Ley Matampi','GK',16,'FK Vojvodina'),
  ('COD','Arnold Alabi','GK',23,'Reims'),
  ('COD','Chancel Mbemba','DEF',5,'Marseille'),
  ('COD','Cédric Bakambu','FWD',9,'Beijing Guoan'),
  ('COD','Gaël Kakuta','MID',10,'Amiens'),
  ('COD','Dodi Lukébakio','FWD',11,'Sevilla'),
  ('COD','Yoane Wissa','FWD',7,'Brentford'),
  ('COD','Arthur Masuaku','DEF',3,'West Ham United'),
  ('COD','Jordan Botaka','MID',17,'Luzern'),
  ('COD','Marcel Tisserand','DEF',4,'Fenerbahçe'),
  ('COD','Merveille Bongonda','MID',19,'Genk'),
  ('COD','Christian Luyindama','DEF',6,'Galatasaray'),
  ('COD','Siméon Niyizonkiza','DEF',2,'Djurgardens'),
  ('COD','Jonathan Bolingi','FWD',21,'Kasimpasa'),
  ('COD','Cédric Omoigui','DEF',14,'Ankaragücü'),
  ('COD','Ngonda Muzinga','MID',8,'Sint-Truiden'),
  ('COD','Francis Amuzu','MID',11,'Anderlecht'),

  -- Uzbekistan
  ('UZB','Utkir Yusupov','GK',1,'Pakhtakor'),
  ('UZB','Abduvohid Nishonov','GK',12,'Lokomotiv Tashkent'),
  ('UZB','Sanjar Kuvvatov','GK',23,'AGMK'),
  ('UZB','Jasur Yakhshiboev','DEF',3,'Pakhtakor'),
  ('UZB','Sherzod Nishonov','DEF',5,'Pakhtakor'),
  ('UZB','Odil Ahmedov','MID',8,'Pakhtakor'),
  ('UZB','Otabek Shukurov','DEF',4,'Lokomotiv Tashkent'),
  ('UZB','Husan Norchaev','DEF',2,'AGMK'),
  ('UZB','Abdulaziz Hasanov','MID',10,'Urawa Red Diamonds'),
  ('UZB','Islom Tukhtakhunov','MID',11,'Busan IPark'),
  ('UZB','Dostonbek Khamdamov','MID',6,'Pakhtakor'),
  ('UZB','Azizbek Turgunboev','MID',14,'AGMK'),
  ('UZB','Eldor Shomurodov','FWD',9,'AS Roma'),
  ('UZB','Bobur Abdixoliqov','FWD',7,'Navbahor Namangan'),
  ('UZB','Jaloliddin Masharipov','FWD',17,'Pakhtakor'),
  ('UZB','Nodirbek Abdusalomov','FWD',19,'AGMK'),
  ('UZB','Vohid Hamrobekov','MID',15,'Lokomotiv Tashkent'),

  -- Colombia
  ('COL','Camilo Vargas','GK',1,'Atlanta United'),
  ('COL','David Ospina','GK',12,'Al-Qadsiah'),
  ('COL','Stefan Medina','DEF',2,'Monterrey'),
  ('COL','Davinson Sánchez','DEF',5,'Galatasaray'),
  ('COL','Yerry Mina','DEF',13,'Valencia'),
  ('COL','Carlos Cuesta','DEF',3,'Genk'),
  ('COL','Johan Mojica','DEF',16,'Real Betis'),
  ('COL','Daniel Muñoz','DEF',18,'Crystal Palace'),
  ('COL','Jhon Lucumí','DEF',4,'Bologna'),
  ('COL','James Rodríguez','MID',10,'Rayo Vallecano'),
  ('COL','Wilmar Barrios','MID',8,'Zenit'),
  ('COL','Mateus Uribe','MID',11,'Porto'),
  ('COL','Gustavo Puerta','MID',14,'Bayer Leverkusen'),
  ('COL','Juan Guillermo Cuadrado','MID',11,'Inter Milan'),
  ('COL','Luis Díaz','FWD',7,'Liverpool'),
  ('COL','Jhon Durán','FWD',9,'Aston Villa'),
  ('COL','Rafael Santos Borré','FWD',19,'Eintracht Frankfurt'),
  ('COL','Miguel Ángel Borja','FWD',21,'River Plate'),

  -- ═══════════════════════════════════════════════════════════════════
  -- GROUP L: England · Croatia · Ghana · Panama
  -- ═══════════════════════════════════════════════════════════════════

  -- England
  ('ENG','Jordan Pickford','GK',1,'Everton'),
  ('ENG','Dean Henderson','GK',13,'Crystal Palace'),
  ('ENG','Sam Johnstone','GK',12,'Crystal Palace'),
  ('ENG','Trent Alexander-Arnold','DEF',2,'Real Madrid'),
  ('ENG','Luke Shaw','DEF',3,'Manchester United'),
  ('ENG','John Stones','DEF',5,'Manchester City'),
  ('ENG','Harry Maguire','DEF',6,'Manchester United'),
  ('ENG','Kyle Walker','DEF',2,'Manchester City'),
  ('ENG','Levi Colwill','DEF',4,'Chelsea'),
  ('ENG','Jude Bellingham','MID',22,'Real Madrid'),
  ('ENG','Declan Rice','MID',4,'Arsenal'),
  ('ENG','Kobbie Mainoo','MID',10,'Manchester United'),
  ('ENG','Connor Gallagher','MID',8,'Chelsea'),
  ('ENG','Phil Foden','MID',7,'Manchester City'),
  ('ENG','Harry Kane','FWD',9,'Bayern Munich'),
  ('ENG','Bukayo Saka','FWD',7,'Arsenal'),
  ('ENG','Marcus Rashford','FWD',11,'Manchester United'),
  ('ENG','Ollie Watkins','FWD',9,'Aston Villa'),
  ('ENG','Cole Palmer','FWD',20,'Chelsea'),

  -- Croatia
  ('CRO','Dominik Livaković','GK',1,'Fenerbahçe'),
  ('CRO','Ivo Grbić','GK',12,'Atlético Madrid'),
  ('CRO','Nediljko Labrović','GK',23,'Hajduk Split'),
  ('CRO','Joško Gvardiol','DEF',2,'Manchester City'),
  ('CRO','Josip Stanišić','DEF',4,'Bayer Leverkusen'),
  ('CRO','Dejan Lovren','DEF',3,'Zenit'),
  ('CRO','Borna Sosa','DEF',17,'Stuttgart'),
  ('CRO','Josip Juranović','DEF',16,'Celtic'),
  ('CRO','Duje Ćaleta-Car','DEF',5,'Southampton'),
  ('CRO','Luka Modrić','MID',10,'Real Madrid'),
  ('CRO','Mateo Kovačić','MID',8,'Manchester City'),
  ('CRO','Marcelo Brozović','MID',11,'Al-Nassr'),
  ('CRO','Mario Pašalić','MID',14,'Atalanta'),
  ('CRO','Luka Ivanušec','MID',20,'Olympiacos'),
  ('CRO','Ivan Perišić','FWD',4,'Hajduk Split'),
  ('CRO','Bruno Petković','FWD',13,'Zenit'),
  ('CRO','Andrej Kramarić','FWD',9,'TSG Hoffenheim'),
  ('CRO','Ante Budimir','FWD',19,'Osasuna'),

  -- Ghana
  ('GHA','Lawrence Ati-Zigi','GK',1,'St. Gallen'),
  ('GHA','Joe Wollacott','GK',16,'Charlton Athletic'),
  ('GHA','Danlad Ibrahim','GK',12,'Asante Kotoko'),
  ('GHA','Daniel Amartey','DEF',5,'Leicester City'),
  ('GHA','Alexander Djiku','DEF',3,'Strasbourg'),
  ('GHA','Abdul Rahman Baba','DEF',14,'Reading'),
  ('GHA','Tariq Lamptey','DEF',2,'Brighton'),
  ('GHA','Dennis Odoi','DEF',15,'Club Brugge'),
  ('GHA','Jonathan Mensah','DEF',4,'Columbus Crew'),
  ('GHA','Thomas Partey','MID',5,'Arsenal'),
  ('GHA','Mubarak Wakaso','MID',14,'Jiangsu Suning'),
  ('GHA','André Ayew','MID',10,'Le Havre'),
  ('GHA','Iddrisu Baba','MID',6,'Mallorca'),
  ('GHA','Elisha Owusu','MID',8,'Gent'),
  ('GHA','Mohammed Kudus','FWD',11,'West Ham United'),
  ('GHA','Iñaki Williams','FWD',9,'Athletic Bilbao'),
  ('GHA','Jordan Ayew','FWD',17,'Crystal Palace'),
  ('GHA','Osman Bukari','FWD',19,'Red Star Belgrade'),

  -- Panama
  ('PAN','Luis Mejía','GK',1,'FC Wil'),
  ('PAN','Orlando Mosquera','GK',12,'Deportivo Cali'),
  ('PAN','Jaime Penedo','GK',22,'unattached'),
  ('PAN','Harold Cummings','DEF',5,'Santos Laguna'),
  ('PAN','Fidel Escobar','DEF',3,'New England Revolution'),
  ('PAN','Eric Davis','DEF',14,'Columbus Crew'),
  ('PAN','Roderick Miller','DEF',4,'Cartagena'),
  ('PAN','Michael Amir Murillo','DEF',2,'Anderlecht'),
  ('PAN','César Blackman','DEF',16,'Valladolid'),
  ('PAN','Adalberto Carrasquilla','MID',8,'Granada'),
  ('PAN','Edgar Bárcenas','MID',11,'Albacete'),
  ('PAN','Aníbal Godoy','MID',6,'Nashville SC'),
  ('PAN','Alberto Quintero','MID',10,'Club Plaza Amador'),
  ('PAN','Gabriel Torres','MID',14,'CD Olimpia'),
  ('PAN','José Fajardo','FWD',9,'FC Dallas'),
  ('PAN','Rolando Blackburn','FWD',7,'Club Olimpia'),
  ('PAN','Ismael Díaz','FWD',17,'Panathinaikos'),
  ('PAN','Cecilio Waterman','FWD',19,'CD FAS')

) AS p(code, nm, pos, num, club)
JOIN t ON t.fifa_code = p.code;
